# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sundial < Formula
  desc "A simple CLI program to print the percent through the day or night."
  homepage "https://github.com/riley-martine/sundial"
  version "1.0.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/riley-martine/sundial/releases/download/v1.0.8/sundial_Darwin_arm64.tar.gz"
      sha256 "cabbe9509810e0915259f1b98a5149d5fad191f98e6a3a14292e8aecfb0a0dae"

      def install
        bin.install "sundial"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/riley-martine/sundial/releases/download/v1.0.8/sundial_Darwin_x86_64.tar.gz"
      sha256 "64d491637a0311b0c12b90ed869b43e13e95216dc9be37eab6e721d7d427638f"

      def install
        bin.install "sundial"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/riley-martine/sundial/releases/download/v1.0.8/sundial_Linux_x86_64.tar.gz"
      sha256 "43a113d9cdba326fc9d65f4eb159ff665c4b6f68b4c29528a2cb1e24cfea9e44"

      def install
        bin.install "sundial"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/riley-martine/sundial/releases/download/v1.0.8/sundial_Linux_arm64.tar.gz"
      sha256 "6e58ef18f295df8150b071fdb822baba61fb9ece2bf8afc7daabcc3ca760e604"

      def install
        bin.install "sundial"
      end
    end
  end

  test do
    system "#{bin}/sundial -version"
  end
end
